# Generated by Django 4.0.3 on 2022-04-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'adm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassLayout',
            fields=[
                ('class_type', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'class_layout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passcode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FareLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_type', models.CharField(blank=True, max_length=30, null=True)),
                ('additional_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'fare_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('stat', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_option', models.CharField(blank=True, max_length=10, null=True)),
                ('class_type', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeatNo',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'seat_no',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('st_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Struct',
            fields=[
                ('train_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('class_type', models.CharField(max_length=2)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'struct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trip_no', models.IntegerField(blank=True, null=True)),
                ('week_no', models.IntegerField(blank=True, null=True)),
                ('fare', models.IntegerField()),
                ('booking_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=120)),
                ('train_type', models.CharField(max_length=30)),
                ('pantry_avl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('first_line', models.CharField(max_length=255)),
                ('second_line', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('coach_no', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('class_type', models.CharField(max_length=20)),
                ('pnr', models.OneToOneField(db_column='pnr', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='test.ticket')),
            ],
            options={
                'db_table': 'reserve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sched',
            fields=[
                ('train_no', models.OneToOneField(db_column='train_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='test.train')),
                ('trip_no', models.IntegerField()),
            ],
            options={
                'db_table': 'sched',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('train_no', models.OneToOneField(db_column='train_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='test.train')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('dist', models.IntegerField(blank=True, null=True)),
                ('day_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_table',
                'managed': False,
            },
        ),
    ]
