# Generated by Django 4.0.3 on 2022-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adm',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='ClassLayout',
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='FareLookup',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='sched',
            name='train_no',
        ),
        migrations.DeleteModel(
            name='SeatNo',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Struct',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='train_no',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Sched',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
