
INSERT INTO train VALUES
(22210,'New Delhi Mumbai Central DURONTO','NDLS','MMCT','DUR'),
(22908,'Hapa Madgaon MADGAON SUPERFAST','HAPA','MAO','SF'),
(53181,'Sealdah Lalgola LALGOLA PASSENGER','SDAH','LGL','PASS'),
(16865,'Chennai Egmore Thanjavur UZHAVAN EXPRESS','MS','TJ','EXP'),
(12057,'New Delhi Una Himachal JAN SHATABDI','NDLS','UHL','JSTBDI'),
(15273,'RAXAUL JN DELHI SATYAGRAH EXPRESS','RXL','ANVT','EXP'),
(11123,'Barauni Jn Gwalior Jn MAIL','GWL','BJU','EXP'),
(22402,'Udhampur Delhi S Rohilla AC SUPERFAST','UHP','DEE','SF'),
(22150,'Pune Jn Ernakulam Jn SUPERFAST EXPRESS','PUNE','ERS','SF'),
(15232,'Gondia Jn Barauni Jn GONDIA EXPRESS','G','BJU','EXP'),
(13416,'Patna Jn Malda Town EXPRESS','PNBE','MLDT','EXP'),
(14038,'NDLS SCL PSK EXP','NDLS','SCL','EXP'),
(16574,'PUDUCHERRY YESVANTPUR JN YESVANTPUR EXPRESS','PDY','YPR','EXP'),
(12360,'Patna Jn Kolkata KOL GARIB RATH','PNBE','KOAA','GR'),
(04602,'JDNX PTK SPL','JDNX','PTK','SPL'),
(04410,'SSB-PWL EMU MEXP SPL','SSB','PWL','SPL'),
(12986,'Delhi S Rohilla Jaipur Jn DOUBLE DECKER','DEE','JP','ICE'),
(15635,'Okha Guwahati GUWAHATI EXPRESS','OKHA','GHY','EXP'),
(06745,'SPE-NLR MEMU EXP SPL','SPE','NLR','SPL'),
(15648,'Guwahati Lokmanyatilak EXPRESSS','GHY','LTT','EXP'),
(19301,'Indore Jn Bg Yasvantpur Jn YESHVANTPUR EXPRESS','DADN','YPR','EXP'),
(13064,'Balurghat Howrah Jn EXPRESS','BLGT','HWH','EXP'),
(18201,'DURG NAUTANWA EXPRESS','DURG','NTV','EXP'),
(22627,'Tiruchchirappalli Jn Thiruvananthapuram Central EXPRESS','TPJ','TVC','ICE'),
(12621,'Chennai Central New Delhi TAMIL NADU EXPRESS','MAS','NDLS','SF'),
(04502,'UHL-SRE MEX SPL','UHL','SRE','SPL'),
(16053,'Chennai Central Tirupati TIRUPATHI EXPRESS','MAS','TPTY','ICE'),
(07507,'RDP - SGUJ DMU SPECIAL','RDP','SGUJ','SPL'),
(14711,'Haridwar Jn Shri Ganganagar EXPRESS','HW','SGNR','ICE'),
(22847,'Visakhapatnam Lokmanyatilak EXPRESS','VSKP','LTT','SF'),
(12804,'Hazrat Nizamuddin Visakhapatnam SWARNA JAYANTI EXPRESS','NZM','VSKP','SF'),
(09429,'ANND-CBY DEMU SPL','ANND','CBY','SPL'),
(12009,'Mumbai Central Ahmedabad Jn SHATABDI EXPRESS','MMCT','GNC','STBDI'),
(16231,'Mayiladuturai Jn Mysore Jn MYSORE EXPRESS','MV','MYS','EXP'),
(05216,'NKE MFP SPL','NKE','MFP','SPL'),
(55149,'Gorakhpur BCY PASSENGER','GKP','BCY','PASS'),
(12371,'HOWRAH JN JAISALMER EXPRESS','HWH','BKN','SF'),
(12620,'Mangalore Central Lokmanyatilak MATSYAGANDA EXPRESS','MAQ','LTT','SF'),
(12554,'New Delhi Barauni Jn VAISHALI EXPRESS','NDLS','SHC','SF'),
(11703,'REWA DR AMBEDKAR NGR (MHOW) INDB EXPRESS','REWA','DADN','EXP'),
(04701,'BTI LGH SPL','BTI','LGH','SPL'),
(12274,'New Delhi Howrah Jn DURONTO EXPRESS','NDLS','HWH','DUR'),
(12990,'Ajmer Jn Dadar Wr  EXPRESS','AII','DDR','SF'),
(12588,'Jammu Tawi Gorakhpur JAMMU EXPRESS','JAT','GKP','SF'),
(14616,'Amritsar Jn Lal Kuan EXPRESS','ASR','LKU','EXP'),
(19414,'KOLKATA AHMEDABAD JN EXPRESS','KOAA','ADI','EXP'),
(12225,'Azamgarh Delhi KAIFIYAT EXPRESS','AMH','DLI','SF'),
(19034,'Ahmedabad Jn Valsad GUJARAT QUEEN','ADI','BL','ICE'),
(17019,'JAIPUR JN HYDERABAD DECCAN EXPRESS','JP','HYB','EXP'),
(17064,'Secunderabad Jn Manmad Jn AJANTA EXPRESS','SC','MMR','EXP'),
(12791,'Secunderabad Jn Danapur EXPRESS','SC','DNR','SF'),
(15644,'Kamakhya Jn Puri EXPRESS','KYQ','PURI','EXP'),
(16533,'Bhagat Ki Kothi Ksr Bengaluru EXPRESS','JU','SBC','EXP'),
(13186,'Jaynagar Sealdah GANGA SAGAR EXPRESS','JYG','SDAH','EXP'),
(13281,'New Tinsukia Rajendranagar T EXPRESS','DBRG','RJPB','EXP'),
(16779,'TIRUPATI RAMESWARAM EXPRESS','TPTY','RMM','EXP'),
(14853,'Varanasi Jn Jodhpur Jn MARUDHAR EXPRESS','BSB','JU','EXP'),
(13166,'Sitamarhi Kolkata EXPRESS','SMI','KOAA','EXP'),
(12635,'Chennai Egmore Madurai Jn VAIGAI EXPRESS','MS','MDU','ICE'),
(12445,'New Delhi Shmata Vd Katra UTTAR SAMPARK KRANTI','NDLS','SVDK','EXP'),
(12350,'New Delhi Bhagalpur EXPRESS','NDLS','GODA','SF'),
(12828,'Purulia Jn Howrah Jn EXPRESS','PRR','HWH','ICE'),
(12622,'New Delhi Chennai Central TAMIL NADU EXPRESS','NDLS','MAS','SF'),
(12788,'NSL NS SPL','NSL','NS','SPL'),
(19329,'Indore Jn Bg Udaipur City VEER BHUMI EXPRESS','INDB','UDZ','EXP'),
(16589,'Ksr Bengaluru C Sahumaharaj T Kolhapur RANI CHENNAMMA EXPRESS','SBC','MRJ','EXP'),
(22131,'Pune Jn Manduadih GYAN GANGA EXPRESS','PUNE','BSBS','SF'),
(13114,'Lalgola Kolkata HAZARDUARI EXPRESS','LGL','KOAA','ICE'),
(12196,'Ajmer Jn Agra Fort INTERCITY','AII','AF','ICE'),
(12346,'Guwahati Howrah Jn SARAIGHAT EXPRESS','GHY','HWH','SF'),
(11061,'Lokmanyatilak Darbhanga Jn DARBHANGA EXPRESS','LTT','JYG','EXP'),
(12750,'BIDR MTM SF EXP','BIDR','MTM','SF'),
(12520,'Kamakhya Jn Lokmanyatilak AC EXPRESS','KYQ','LTT','SF'),
(12535,'Lucknow Ne Raipur Jn GARIBRATH','LJN','R','GR'),
(19408,'Varanasi Jn Ahmedabad Jn EXPRESS','BSB','ADI','EXP'),
(22883,'Puri Yasvantpur Jn GARIB RATH','PURI','YPR','GR'),
(22620,'Tirunelveli Bilaspur Jn BILASPUR EXPRESS','TEN','BSP','SF'),
(15716,'Ajmer Jn Kishanganj GARIB NAWAJ EXPRESS','AII','KNE','EXP'),
(17221,'Kakinada Port Lokmanyatilak  EXPRESS','COA','LTT','EXP'),
(12970,'Jaipur Jn Coimbatore Jn SUPERFAST EXPRESS','JP','CBE','SF'),
(12055,'New Delhi Dehradun JAN SHATABDI','NDLS','DDN','JSTBDI'),
(22863,'Howrah Jn Yasvantpur Jn AC EXPRESS','HWH','YPR','SF'),
(15055,'Agra Fort Ramnagar EXPRESS','AF','RMR','EXP'),
(12291,'Yasvantpur Jn Chennai Central CHENNAI EXPRESS','YPR','MAS','SF'),
(13483,'Malda Town Delhi FARAKKA EXPRESS','MLDT','DLI','EXP'),
(22845,'Pune Jn Hatia HATIA SUPERFAST','HTE','PUNE','SF'),
(19608,'Ajmer Jn Kolkata EXPRESS','MDJN','KOAA','EXP'),
(12411,'Chandigarh Amritsar Jn INTERCITY EXPRESS','CDG','ASR','ICE'),
(19224,'Jammu Tawi Ahmedabad Jn EXPRESS','JAT','ADI','MAIL'),
(19610,'HW UDZ  EXP','YNRK','UDZ','EXP'),
(14631,'Dehradun Amritsar Jn EXPRESS','DDN','ASR','EXP'),
(12382,'New Delhi Howrah Jn POORVA EXPRESS','NDLS','HWH','SPL'),
(16342,'TVC GUV EXP','TVC','GUV','SPL'),
(12228,'INDORE JN BG MUMBAI CENTRAL MUMBAI DURONTO','INDB','MMCT','DUR'),
(13345,'Varanasi Jn Singrauli INTERCITY','BSB','SGRL','ICE'),
(12558,'Anand Vihar Terminal Muzaffarpur Jn SAPT KRANTI EXPRESS','ANVT','MFP','SF'),
(12783,'Visakhapatnam Secunderabad Jn AC EXPRESS','VSKP','SC','SF'),
(16535,'Mysore Jn Solapur Jn GOLGUMBAZ EXPRESS','MYS','SUR','EXP'),
(12539,'YASVANTPUR JN LUCKNOW LUCKNOW EXPRESS','YPR','LKO','SF'),
(18048,'Vasco Da Gama Kacheguda HOWRAH EXPRESS','VSG','SHM','EXP'),
(12077,'Chennai Central Vijayawada Jn JAN SHATABDI','MAS','BZA','JSTBDI'),
(12985,'Jaipur Jn Delhi S Rohilla DOUBLE DECKER','JP','DEE','ICE'),
(11464,'JABALPUR SOMNATH SOMNATH EXPRESS','JBP','SMNH','EXP'),
(12223,'Lokmanyatilak Ernakulam Jn DURONTO','LTT','ERS','DUR'),
(12128,'Pune Jn Mumbai Cst INTERCITY EXPRESS','PUNE','CSMT','ICE'),
(15052,'Gorakhpur Kolkata KOLKATA EXPRESS','GKP','KOAA','EXP'),
(15661,'RANCHI KAMAKHYA JN  EXPRESS','RNC','KYQ','EXP'),
(22187,'Habibganj Jabalpur INTERCITY EXPRESS','RKMP','ADTL','ICE'),
(09535,'DADN RTM DEMU SPL','DADN','RTM','SPL'),
(22611,'Chennai Central New Jalpaiguri EXPRESS','MAS','NJP','SF'),
(12839,'Howrah Jn Chennai Central MAIL','HWH','MAS','SF'),
(18234,'Bilaspur Jn Indore Jn Bg NARMADA EXPRESS PASSENGER','BSP','INDB','MAIL'),
(22113,'Lokmanyatilak Kochuveli EXPRESS','LTT','KCVL','SF'),
(15029,'Gorakhpur Pune Jn EXPRESS','GKP','PUNE','EXP'),
(17411,'Mumbai Cst C Sahumaharaj T Kolhapur MAHALAXMI EXPRESS','CSMT','KOP','EXP'),
(12032,'Amritsar Jn New Delhi AMRITSAR SHATABDI','ASR','NDLS','STBDI'),
(14003,'Malda Town New Delhi EXPRESS','MLDT','NDLS','EXP'),
(13346,'Singrauli Varanasi Jn INTERCITY EXPRESS','SGRL','BSB','ICE'),
(15013,'Jaisalmer Ramnagar RANIKHET EXPRESS','JSM','KGM','EXP'),
(12636,'Madurai Jn Chennai Egmore VAIGAI EXPRESS','MDU','MS','ICE'),
(22884,'Yasvantpur Jn Puri GARIB RATH','YPR','PURI','GR'),
(14220,'Lucknow Varanasi Jn EXPRESS','LKO','BSB','ICE'),
(19052,'Muzaffarpur Jn Valsad SHRAMIK EXPRESS','MFP','BL','EXP'),
(12435,'JYG ANVT G RATH','JYG','ANVT','GR'),
(15903,'Dibrugarh Chandigarh EXPRESS','DBRG','CDG','EXP'),
(12367,'Bhagalpur Anand Vihar Terminal VIKRAMSHILA EXPRESS','BGP','ANVT','SF'),
(12827,'Howrah Jn Purulia Jn EXPRESS','HWH','PRR','ICE'),
(22484,'Gandhidham Jn Jodhpur Jn JODHPUR EXPRESS','GIMB','JU','SF'),
(12273,'Howrah Jn New Delhi DURONTO','HWH','NDLS','DUR'),
(12591,'GORAKHPUR YASVANTPUR JN EXPRESS','GKP','YPR','SF'),
(18241,'Durg Ambikapur EXPRESS PASSENGER','DURG','ABKP','MAIL'),
(04153,'RBL-CNB UNRESERVED SPL','RBL','CNB','SPL'),
(11009,'Mumbai Cst Pune Jn SINHAGAD EXPRESS','CSMT','PUNE','ICE'),
(12424,'New Delhi Dibrugarh Town RAJDHANI','NDLS','DBRG','RAJ'),
(14209,'Prayag Jn Lucknow INTRCTY','PYGS','LKO','ICE'),
(12285,'Secunderabad Jn Hazrat Nizamuddin DURONTO  EXPRESS','SC','NZM','DUR'),
(12284,'Hazrat Nizamuddin Ernakulam Jn DURONTO','NZM','ERS','DUR'),
(15666,'DIMAPUR KAMAKHYA JN B G EXPRESS','MXN','GHY','EXP'),
(11450,'Shmata Vd Katra Jabalpur EXPRESS','SVDK','JBP','EXP'),
(14525,'Ambala Cant Jn Shri Ganganagar INTERCITY','UMB','SGNR','ICE'),
(12742,'Patna Jn Vasco Da Gama EXPRESS','PNBE','VSG','SF'),
(14312,'Bhuj Bareilly ALA HAZRAT EXPRESS','BHUJ','BE','EXP'),
(12852,'Chennai Central Bilaspur Jn BILASPUR EXPRESS','MAS','BSP','SF'),
(12623,'Chennai Central Thiruvananthapuram Central TRIVANDRUM MAIL','MAS','TVC','SF'),
(12577,'Darbhanga Jn Mysore Jn BAGMATI EXPRESS','DBG','MYS','SF'),
(14114,'Dehradun Allahabad Jn LINK EXPRESS','DDN','SFG','MAIL'),
(12918,'HAZRAT NIZAMUDDIN AHMEDABAD JN GUJRAT SAMPARK KRANTI EXPRESS','NZM','ADI','EXP'),
(17609,'Patna Jn Purna Jn  EXPRESS','PNBE','PAU','EXP'),
(22351,'Patliputra Yasvantpur Jn EXPRESS','PPTA','YPR','SF'),
(12509,'Bengaluru Cant Guwahati GUWAHATI EXPRESS','BNC','GHY','SF'),
(12660,'Shalimar Nagarcoil Jn GURUDEV EXPRESS','SHM','NCJ','SF'),
(12694,'Tuticorin Chennai Egmore PEARL CITY EXPRESS','TN','MS','SF'),
(17001,'Sainagar Shirdi Secunderabad Jn EXPRESS','SNSI','SC','EXP'),
(22406,'Anand Vihar Terminal Bhagalpur GARIB RATH','ANVT','BGP','GR'),
(12673,'Chennai Central Coimbatore Jn CHERAN EXPRESS','MAS','CBE','SF'),
(13245,'New Jalpaiguri Rajendranagar T CAPITAL EXPRESS','NJP','RJPB','EXP'),
(22413,'MADGAON HAZRAT NIZAMUDDIN RAJDHANI','MAO','NZM','RAJ'),
(11271,'ITARSI JN BHOPAL JN VINDHYACHAL EXPRESS','ET','BPL','EXP'),
(22119,'MUMBAI CST KARMALI TEJAS EXPRESS','CSMT','KRMI','STBDI'),
(22682,'Chennai Central Mysore Jn MYSORE EXPRESS','MAS','MYS','SF'),
(12477,'Jamnagar Shmata Vd Katra EXPRESS','JAM','SVDK','SF'),
(16352,'Nagarcoil Jn Mumbai Cst MUMBAI EXPRESS','NCJ','CSMT','EXP'),
(22634,'Hazrat Nizamuddin Thiruvananthapuram Central SUPERFAST EXPRESS','NZM','TVC','SF'),
(12311,'Howrah Jn Kalka DELHI MAIL','HWH','KLK','SF'),
(11449,'Jabalpur Shmata Vd Katra EXPRESS','JBP','SVDK','EXP'),
(06624,'BRGW-KTE MEMU PSPC SPL','BRGW','KTE','SPL'),
(12882,'Puri Howrah Jn GARIB RATH','PURI','SHM','GR'),
(14216,'Lucknow Allahabad Jn GANGA GOMTI EXPRESS','LKO','PYGS','ICE'),
(03572,'MKA - JSME MEMU PGR SPL','MKA','JSME','SPL'),
(12378,'New Alipurduar Sealdah PADATIK EXPRESS','NOQ','SDAH','SF'),
(12201,'Lokmanyatilak Kochuveli GARIB RATH','LTT','KCVL','GR'),
(12738,'Secunderabad Jn Kakinada Port GOUTAMI EXPRESS','LPI','COA','SF'),
(22401,'Delhi S Rohilla Udhampur AC SUPERFAST','DEE','UHP','SF'),
(12912,'Haridwar Jn Valsad SUPERFAST EXPRESS','HW','BL','SF'),
(11040,'Gondia Jn C Sahumaharaj T Kolhapur MAHARASHTRA EXPRESS','G','KOP','EXP'),
(06552,'JTJ-SBC MEMU','JTJ','SBC','SPL'),
(11039,'C Sahumaharaj T Kolhapur Gondia Jn MAHARASHTRA EXPRESS','KOP','G','EXP'),
(22633,'Thiruvananthapuram Central Hazrat Nizamuddin NIZAMUDDIN EXPRESS','TVC','NZM','SF'),
(16613,'Rajkot Jn Coimbatore Jn COIMBATORE EXPRESS','RJT','CBE','EXP'),
(22806,'Anand Vihar Terminal Bhubaneswar SUPERFAST','ANVT','BBS','SF'),
(12306,'New Delhi Howrah Jn KOLKATA  RAJDHANI','NDLS','HWH','RAJ'),
(12231,'LUCKNOW CHANDIGARH EXPRESS','LKO','CDG','SF'),
(22917,'Bandra Terminus Haridwar Jn HARIDWAR EXPRESS','BDTS','HW','SF'),
(11022,'Tirunelveli Dadar CHALUKYA  EXPRESS','TEN','DR','EXP'),
(12430,'New Delhi Lucknow AC SUPERFAST','NDLS','LKO','SF'),
(12164,'MAS LTT EXPRESS','MAS','LTT','SF'),
(19568,'Okha Tuticorin VIVEK EXPRESS','OKHA','TN','EXP'),
(12540,'Lucknow Yasvantpur Jn SUPERFAST EXPRESS','LKO','YPR','SF'),
(12434,'HAZRAT NIZAMUDDIN CHENNAI CENTRAL CHENNAI RAJDHANI','NZM','MAS','RAJ'),
(19168,'Varanasi Jn Ahmedabad Jn SABARMATI EXPRESS','BSB','ADI','MAIL'),
(22455,'Sainagar Shirdi Kalka SUPERFAST EXPRESS','SNSI','KLK','SF'),
(12314,'New Delhi Sealdah SEALDAH RAJDHANI','NDLS','SDAH','RAJ'),
(21125,'RTM  BHIND EXP','RTM','BIX','EXP'),
(15028,'Gorakhpur Hatia MAURYA EXPRESS','GKP','HTE','EXP'),
(22424,'Amritsar Jn Gorakhpur EXPRESS','ASR','GKP','SF'),
(15104,'Manduadih Gorakhpur INTERCITY','BSBS','GKP','ICE'),
(12964,'Udaipur City Hazrat Nizamuddin MEWAR EXPRESS','UDZ','NZM','SF'),
(12643,'THIRUVANANTHAPURAM CENTRAL HAZRAT NIZAMUDDIN NIZAMUDDIN EXPRESS','TVC','NZM','SF'),
(19574,'Jaipur Jn Okha EXPRESS','JP','OKHA','EXP'),
(12849,'Bilaspur Jn Pune Jn SUPERFAST EXPRESS','BSP','PUNE','SF'),
(11465,'Somnath Jabalpur EXPRESS','SMNH','JBP','EXP'),
(07327,'MYS-CMNR PAS SPL','MYS','CMNR','SPL'),
(16311,'BIKANER JN KOCHUVELI EXPRESS','SGNR','KCVL','EXP'),
(22104,'Faizabad Jn Lokmanyatilak SUPERFAST EXPRESS','AYC','LTT','SF'),
(15813,'DKGN-MZS EXPRESS','DKGN','MZS','SPL'),
(72452,'Shimla Kalka RAIL MOTOR','SML','KLK','HILL'),
(12241,'Chandigarh Amritsar Jn SUPERFAST','CDG','ASR','ICE'),
(12902,'AHMEDABAD JN MUMBAI CENTRAL GUJARAT MAIL','ADI','DDR','SF'),
(12152,'Howrah Jn Lokmanyatilak SAMARSATA EXPRESS','SHM','LTT','SF'),
(13163,'SEALDAH SAHARSA JN HATE BAZARE EXPRESS','SDAH','SHC','EXP'),
(12776,'Secunderabad Jn Kakinada Town COCANADA EXPRESS','LPI','CCT','SF'),
(13010,'Dehradun Howrah Jn DOON EXPRESS','YNRK','HWH','EXP'),
(12397,'GAYA JN NEW DELHI MAHABODHI EXPRESS','GAYA','NDLS','SF'),
(16516,'Karwar Yasvantpur Jn EXPRESS','KAWR','YPR','ICE'),
(12336,'Lokmanyatilak Bhagalpur BHAGALPUR EXPRESS','LTT','BGP','SF'),
(18637,'Hatia Bengaluru Cant EXPRESS','HTE','BNC','EXP'),
(22146,'Miraj Jn Pandharpur SUPERFAST EXPRESS','MRJ','PVR','ICE'),
(15656,'Shmata Vd Katra Kamakhya Jn EXPRESS','SVDK','KYQ','EXP'),
(22444,'Bandra Terminus Kanpur Central KANPUR EXPRESS','BDTS','CNB','SF'),
(22451,'Bandra Terminus Chandigarh SUPERFAST','BDTS','CDG','SF'),
(16218,'SAINAGAR SHIRDI MYSORE JN EXPRESS','SNSI','MYS','EXP'),
(06625,'KTE-STA MEMU SPL','KTE','STA','SPL'),
(12996,'Udaipur City Bandra Terminus SUPERFAST EXPRESS','AII','BDTS','SF'),
(16591,'Hubli Jn Mysore Jn HAMPI EXPRESS','UBL','MYS','EXP'),
(10104,'Madgaon Mumbai Cst MANDOVI EXPRESS','MAO','CSMT','ICE'),
(12067,'JAN SHATABDI SPL','GHY','JTTN','SPL'),
(12444,'ANAND VIHAR TERMINAL HALDIA SUPERFAST EXPRESS','ANVT','HLZ','SF'),
(12221,'Pune Jn Howrah Jn DURONTO','PUNE','HWH','DUR'),
(12927,'Mumbai Central Vadodara Jn VADODARA EXPRESS','DDR','EKNR','SF'),
(17302,'Dharwad Mysore Jn MYSORE EXPRESS','DWR','MYS','EXP'),
(22646,'THIRUVANANTHAPURAM CENTRAL INDORE JN BG AHILYANAGARI EXPRESS','KCVL','INDB','SF'),
(14041,'MUSSOORIE EXP','DLI','DDN','EXP'),
(03291,'PPTA-PNBE MEMU PASS SPL','PPTA','PNBE','SPL'),
(06018,'ERS-SRR MEMU EXP SPL','ERS','SRR','SPL'),
(14504,'Shmata Vd Katra Kalka EXPRESS','SVDK','KLK','EXP'),
(22204,'Secunderabad Jn Visakhapatnam DURONTO  EXPRESS','SC','VSKP','DUR'),
(16217,'MYSORE JN SAINAGAR SHIRDI EXPRESS','MYS','SNSI','EXP'),
(12304,'New Delhi Howrah Jn POORVA EXPRESS','NDLS','HWH','SF'),
(12661,'Chennai Egmore Sengottai POTHIGAI  EXPRESS','MS','SCT','SF'),
(15008,'Lucknow Ne Varanasi City   EXPRESS','LJN','BCY','EXP'),
(12155,'Habibganj Hazrat Nizamuddin BHOPAL EXPRESS','RKMP','NZM','SF'),
(18450,'Patna Jn Puri B NATH DHAM EXPRESS','PNBE','PURI','EXP'),
(03453,'TIL-JMP PGR SPL','TIL','JMP','SPL'),
(22149,'Ernakulam Jn Pune Jn EXPRESS','ERS','PUNE','SF'),
(19415,'Ahmedabad Jn Shmata Vd Katra EXPRESS','ADI','SVDK','EXP'),
(11272,'Bhopal Jn Itarsi Jn VINDHYACHAL EXPRESS','BPL','ET','EXP'),
(18106,'PURI ROU SPL','JYG','ROU','SPL'),
(12235,'HUMSAFAR EXP','MDP','ANVT','EXP'),
(14235,'Varanasi Jn Bareilly EXPRESS','BSB','BE','EXP'),
(13352,'Alleppey Dhanbad Jn DHANBAD EXPRESS','ALLP','DHN','EXP'),
(12425,'New Delhi Jammu Tawi JAMMU RAJDHANI','NDLS','JAT','RAJ'),
(03558,'ASN-BWN MEMU PGR SPL','ASN','BWN','SPL'),
(14012,'Hoshiarpur Delhi EXPRESS','HSX','DLI','EXP'),
(16316,'Kochuveli Ksr Bengaluru BANGALORE EXPRESS','KCVL','MYS','EXP'),
(22619,'Bilaspur Jn Tirunelveli EXPRESS','BSP','TEN','SF'),
(22939,'Hapa Bilaspur Jn EXPRESS','HAPA','BSP','SF'),
(12647,'Coimbatore Jn Hazrat Nizamuddin KONGU EXPRESS','CBE','NZM','SF'),
(12217,'Kochuveli Chandigarh SAMPARK KRANTI','KCVL','CDG','EXP'),
(12469,'Kanpur Central Jammu Tawi EXPRESS','CNB','JAT','SF'),
(03327,'SNDT-GMO PASSENGER  SPL','SNDT','GMO','SPL'),
(22101,'LTT MDU SF SPL','LTT','MDU','ICE'),
(12901,'Mumbai Central Ahmedabad Jn GUJARAT MAIL','DDR','ADI','SF'),
(16106,'TIRUCHENDUR CHENNAI EGMORE CHENNAI EXPRESS','TCN','MS','EXP'),
(12492,'Jammu Tawi Barauni Jn MAUR DHAWJ EXPRESS','JAT','BJU','SF'),
(03067,'KWAE-RPH MEMU PGR SPL','KWAE','RPH','SPL'),
(12615,'Chennai Central Delhi S Rohilla GRAND TRUNK EXPRESS','MAS','NDLS','SF'),
(22862,'Adra Jn Shalimar RAJYA RANI EXPRESS','ADRA','SHM','ICE'),
(12870,'Howrah Jn Mumbai Cst EXPRESS','HWH','CSMT','SF'),
(12722,'Hazrat Nizamuddin Hyderabad Decan DAKSHIN EXPRESS','NZM','HYB','SF'),
(12792,'Danapur Secunderabad Jn SECUNDERABAD EXPRESS','DNR','SC','SF'),
(12707,'Tirupati Hazrat Nizamuddin A P SAMPARK KRANTI','TPTY','NZM','EXP'),
(14810,'Jodhpur Jn Jaisalmer EXPRESS','JU','JSM','EXP'),
(14313,'Lokmanyatilak Bareilly BAREILLY EXPRESS','LTT','BE','EXP'),
(12933,'Mumbai Central Ahmedabad Jn KARNAVATI EXPRESS','MMCT','ADI','ICE'),
(14512,'Saharanpur Allahabad Jn NAUCHANDI EXPRESS','SRE','PYGS','EXP'),
(14316,'New Delhi Bareilly INTERCITY EXPRESS','NDLS','BE','ICE'),
(19251,'SOMNATH OKHA EXPRESS','SMNH','OKHA','EXP'),
(12820,'Anand Vihar Terminal Bhubaneswar ORISSA SAMPARK KRANTI','ANVT','BBS','EXP'),
(19409,'Ahmedabad Jn Gorakhpur GORAKHPUR EXPRESS','ADI','GKP','EXP'),
(22873,'Digha F S Visakhapatnam EXPRESS','DGHA','VSKP','SF'),
(15616,'SCL GHY  SPECIAL','SCL','GHY','SPL'),
(14205,'Faizabad Jn Delhi EXPRESS','AYC','DLI','EXP'),
(12372,'JAISALMER HOWRAH JN SUPERFAST EXPRESS','BKN','HWH','SF'),
(22145,'Pandharpur Miraj Jn SUPERFAST EXPRESS','PVR','MRJ','ICE'),
(12119,'Amravati Ajni EXPRESS','AMI','AJNI','ICE'),
(19326,'Amritsar Jn Indore Jn Bg EXPRESS','ASR','INDB','EXP'),
(03209,'KIUL-MKA MEMU PASS SPL','KIUL','MKA','SPL'),
(22652,'PGT MAS EXP','PGT','MAS','SF'),
(17063,'Manmad Jn Secunderabad Jn AJANTA EXPRESS','MMR','SC','EXP'),
(12436,'JYG GARIB RATH','ANVT','JYG','GR'),
(12182,'Ajmer Jn Jabalpur DAYODAYA EXPRESS','AII','JBP','SF'),
(12033,'Kanpur Central New Delhi SHATABDI','CNB','NDLS','STBDI'),
(12754,'MARATHWADA S K','NZM','NED','SF'),
(18409,'Howrah Jn Puri SRI JAGANNATH EXPRESS','SHM','PURI','EXP'),
(19203,'GNC BVC EXPRESS','GNC','BVC','EXP'),
(14042,'Dehradun Delhi S Rohilla MUSSOORIE EXPRESS','DDN','DLI','EXP'),
(12859,'Mumbai Cst Howrah Jn GITANJALI EXPRESS','CSMT','HWH','SF'),
(12786,'Ksr Bengaluru Kacheguda KACHEGUDA EXPRESS','MYS','KCG','SF'),
(12390,'Chennai Egmore Gaya Jn EXPRESS','MAS','GAYA','SF'),
(12002,'New Delhi Habibganj BHOPAL SHATABDI','NDLS','RKMP','STBDI'),
(15036,'Kathgodam Delhi UTR SAMPARK KRANTI EXPRESS','KGM','DLI','EXP'),
(18625,'PRNC HTE EXPRESS','PRNC','HTE','ICE'),
(12582,'New Delhi Manduadih SUPERFAST EXPRESS','NDLS','BSBS','SF');